# Generated by Django 4.1.7 on 2023-04-05 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='zip',
            new_name='zip_code',
        ),
    ]
