# Generated by Django 4.1.7 on 2023-04-09 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('realtors', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='realtor',
            old_name='discription',
            new_name='description',
        ),
    ]
